app:
  title: SIR
  logo: logo.png
  version: '1.0.0'
  help_url: http://www.mhhe.com/business/opsci/sterman/models.mhtml
  colors:
    color_1: '#0072b2' # blue
    color_2: '#d33700' # red
    color_3: '#53bb37' # green
    color_4: '#a7a9ac' # gray
    color_5: '#000000' # black
  initial_view: Models > SIR Model
  track_sliders: true
  sliders:
    Initial Contact Rate:
      label: Initial Contact Rate
      units: per day
      format: '0.0'
      value: 1
      min: 0
      max: 5
      step: 0.1
    Infectivity i:
      label: Infectivity
      units: probability
      format: '0.00'
      value: 0.1
      min: -2
      max: 2
      step: 0.25
    Average Duration of Illness d:
      label: Average Duration of Illness
      units: days
      format: 0a
      value: 2
      min: 0
      max: 10
      step: 1
views:
  - title: Models
    views:
      - title: SIR Model
        graphs:
          - title: Infection and Recovery Rates
            x_axis:
              min: 0
              max: 2000
            y_axis:
              units: people/day
              format: 0a
              min: 0
              max: 1000
            plots:
              - name: Infection Rate
                label: Infection Rate
                color: color_1
                style: line
              - name: Recovery Rate
                label: Recovery Rate
                color: color_2
                style: line
          - title: Population
            x_axis:
              min: 0
              max: 2000
            y_axis:
              units: people
              format: 0a
              min: 0
              max: 12000
            plots:
              - name: Susceptible Population S
                label: Susceptible
                color: color_1
                style: line
              - name: Infectious Population I
                label: Infectious
                color: color_2
                style: line
              - name: Recovered Population R
                label: Recovered
                color: color_3
                style: line
    sliders:
      - Initial Contact Rate
      - Infectivity i
      - Average Duration of Illness d
